package src

STATS_EXP_PICKUP_SIZE :: 5
STATS_EXP_DAMPER :: 0.5
STATS_EXP_MAGNET_SPEED :: 300
STATS_EXP_MIN_SPEED :: 30
STATS_EXP_MAX_SPEED_FACTOR :: 4

STATS_DEFAULT_EXP_POINTS :: 50
STATS_BASE_LEVEL_UP_EXP :: 1000
STATS_LEVEL_UP_EXP_FACTOR :: 1000